name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: /WebAppDotnetCore
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      #working-directory: ./WebAppDotnetCore
      run: dotnet restore
    - name: Build
      #working-directory: ./WebAppDotnetCore
      run: dotnet build --no-restore
    - name: Test
      #working-directory: ./WebAppDotnetCore
      run: dotnet test --no-build --verbosity normal
